Get rid of compilation errors by writing the methods out-of-line.
debug_out(F("Read SDS..."), DEBUG_MIN_INFO, 1);
is causing
member function pgmspace.h:16:51: error: __c causes a section type conflict with __c
if and only if(!) the method containing the call is written inline.